name: 'Update Version Number'
description: 'A GitHub Action to update the version number of a file in a branch and lower branches'
author: 'RecordLinkingLab recordlinkinglab@gmail.com'
inputs:
  token:
    description: 'The bot token to use for the commit'
    required: true
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ inputs.token }} 

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Update Version Number
        shell: bash
        run: |
          COMMIT_MSG=$(python ${{ github.action_path }}/UpdateVersion.py)
          echo $COMMIT_MSG
          echo "COMMIT_MSG=$COMMIT_MSG" >> $GITHUB_ENV
          echo "NEW_VERSION=$(echo $COMMIT_MSG | awk -F'to ' '{print $2}')" >> $GITHUB_ENV

      - name: Commit Version Update
        shell: bash
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _version.py
          git commit -m "${{ env.COMMIT_MSG }}"
          git tag ${{ env.NEW_VERSION }}
          git push
          git push --tags

      - name: Update Lower Level Branch Versions
        shell: bash
        run: |
          branch=$(echo "${GITHUB_REF#refs/heads/}")

          if [ "$branch" = "prd" ]; then
            git checkout stg
            git merge origin/prd --strategy-option theirs
            COMMIT_MSG=$(python ${{ github.action_path }}/UpdateVersion.py)
            NEW_VERSION=$(echo $COMMIT_MSG | awk -F'to ' '{print $2}')
            echo $COMMIT_MSG
            git add _version.py
            git commit -m "$COMMIT_MSG"
            git tag $NEW_VERSION
            git push
            git push --tags
          fi

          if [ "$branch" = "stg" ] || [ "$branch" = "prd" ]; then
            git checkout dev
            git merge origin/stg --strategy-option theirs
            COMMIT_MSG=$(python ${{ github.action_path }}/UpdateVersion.py)
            NEW_VERSION=$(echo $COMMIT_MSG | awk -F'to ' '{print $2}')
            echo $COMMIT_MSG
            git add _version.py
            git commit -m "$COMMIT_MSG"
            git tag $NEW_VERSION
            git push
            git push --tags
          fi
